<?php echo $header; ?>

<h2 class="bits-title mdl-typography--title">Current Events</h2>
<div class="bits-events mdl-grid">
<?php if ($events_current) : ?>
<?php foreach ($events_current as $event) : ?>
  <div class="bits-events__event mdl-card mdl-cell mdl-cell--4-col mdl-shadow--2dp">
    <a href="<?php echo $event['view']; ?>" class="mdl-button mdl-js-ripple-effect mdl-js-button floating mdl-button--fab mdl-color--accent"><i class="material-icons mdl-color-text--white" role="presentation">visibility</i><span class="visuallyhidden">view</span></a>
    <div class="mdl-card__title mdl-card--expand">
      <h4>
        <?php $_($event['title']); ?><br/>
        <?php $_($event['date']); ?>&nbsp;
      </h4>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <i class="material-icons">event</i>
      <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect mdl-js-ripple-effect--ignore-events" for="evt<?php $_($event['id']); ?>">
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['view']; ?>">View event</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['payments']; ?>">Manage payments</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['queue']; ?>">Manage queue</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['add_booking']; ?>">Add booking</li>
      </ul>
      <button id="evt<?php $_($event['id']); ?>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon"><i class="material-icons" role="presentation">more_vert</i>
    </div>
  </div>
<?php endforeach; ?>
<?php else : ?>
  <div class="mdl-cell mdl-cell--12-col">You have no currently active events</div>
<?php endif; ?>
</div>

<h2 class="bits-title mdl-typography--title">Upcoming Events</h2>
<div class="bits-events mdl-grid">
<?php if ($events_queued) : ?>
<?php foreach ($events_queued as $event) : ?>
  <div class="bits-events__event mdl-card mdl-cell mdl-cell--4-col mdl-shadow--2dp">
    <a href="<?php echo $event['view']; ?>" class="mdl-button mdl-js-ripple-effect mdl-js-button floating mdl-button--fab mdl-color--accent"><i class="material-icons mdl-color-text--white" role="presentation">visibility</i><span class="visuallyhidden">view</span></a>
    <div class="mdl-card__title mdl-card--expand">
      <h4>
        <?php $_($event['title']); ?><br/>
        <?php $_($event['date']); ?>&nbsp;
      </h4>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <i class="material-icons">event</i>
      <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect mdl-js-ripple-effect--ignore-events" for="evt<?php $_($event['id']); ?>">
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['view']; ?>">View event</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['payments']; ?>">Manage payments</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['queue']; ?>">Manage queue</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['add_booking']; ?>">Add booking</li>
      </ul>
      <button id="evt<?php $_($event['id']); ?>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon"><i class="material-icons" role="presentation">more_vert</i>
    </div>
  </div>
<?php endforeach; ?>
<?php else : ?>
  <div class="mdl-cell mdl-cell--12-col">You have no events planned for the future</div>
<?php endif; ?>
</div>

<h2 class="bits-title mdl-typography--title">Past Events</h2>
<div class="bits-events mdl-grid">
<?php if ($events_expired) : ?>
<?php foreach ($events_expired as $event) : ?>
  <div class="bits-events__event mdl-card mdl-cell mdl-cell--4-col mdl-shadow--2dp">
    <a href="<?php echo $event['view']; ?>" class="mdl-button mdl-js-ripple-effect mdl-js-button floating mdl-button--fab mdl-color--accent"><i class="material-icons mdl-color-text--white" role="presentation">visibility</i><span class="visuallyhidden">view</span></a>
    <div class="mdl-card__title mdl-card--expand">
      <h4>
        <?php $_($event['title']); ?><br/>
        <?php $_($event['date']); ?>&nbsp;
      </h4>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <i class="material-icons">event</i>
      <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect mdl-js-ripple-effect--ignore-events" for="evt<?php $_($event['id']); ?>">
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['view']; ?>">View event</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['payments']; ?>">Manage payments</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['queue']; ?>">Manage queue</li>
        <li class="mdl-menu__item mdl-js-ripple-effect" tabindex="-1" href="<?php echo $event['add_booking']; ?>">Add booking</li>
      </ul>
      <button id="evt<?php $_($event['id']); ?>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon"><i class="material-icons" role="presentation">more_vert</i></button>
    </div>
  </div>
<?php endforeach; ?>
<?php else : ?>
  <div class="mdl-cell mdl-cell--12-col">You have no past events</div>
<?php endif; ?>
</div>

<?php echo $footer;
