
      </div>
    </main>
    <footer class="bits-layout__footer">
      <div class="bits-layout__content content">
        <p>This online booking system runs on Bitsand, a web-based booking system for LRP events. Bitsand is copyright &copy;<a href="<?php $_($link_download); ?>">The Bitsand Project<?php if ($version) $_(' ' . $version); ?></a>.</p>
      </div>
    </footer>
  </div>

<?php foreach ($scripts as $script) : ?>
  <script src="<?php $_($script['href']); ?>"<?php if ($script['defer']) echo ' defer'; ?>></script>
<?php endforeach; ?>
  <script>
    require(['Admin'], function(Admin) {
<?php if ($messages) : ?>
      Admin.messages(<?php echo $messages; ?>);
<?php endif; ?>
    });
  </script>
</body>
</html>