<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title><?php $_($title); ?></title>
<?php foreach ($styles as $style) : ?>
  <link rel="<?php echo $style['rel']; ?>" type="text/css" href="<?php $_($style['href']); ?>"<?php if ($style['media']) : ?> media="<?php echo $style['media']; ?>"<?php endif; ?> />
<?php endforeach; ?>
<?php /* <script defer src="//cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.2.1/material.min.js"></script> */ ?>
  <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>
  <script>
  requirejs.config({
    baseUrl: '<?php echo $base_path; ?>scripts/',
<?php if (defined('DEVELOPMENT')) echo "     urlArgs: 'bust=' + (new Date()).getTime(),"; ?>
    paths: {
      domReady: ['//cdnjs.cloudflare.com/ajax/libs/require-domReady/2.0.1/domReady.min'],
      jspdf: ['//cdnjs.cloudflare.com/ajax/libs/jspdf/1.2.61/jspdf.min'],
      moment: ['//cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min'],
      pikaday: ['//cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min'],
      ckeditor: ['//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.8.0/ckeditor'],
      'ckeditor-classic': ['//cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor'],
    },
    shim: {
      pikaday: {
        deps: ['moment']
      }
    }
  });
  </script>
<?php foreach ($scripts as $script) : ?>
  <script src="<?php $_($script['href']); ?>"<?php if ($script['defer']) echo ' defer'; ?>></script>
<?php endforeach; ?>

<?php if ($favicon) : ?>
  <link rel="shortcut icon" href="<?php $_($favicon); ?>" />
<?php endif; ?>
</head>
<body>
  <div class="bits-layout__outer">
    <header class="bits-layout__header">
      <div class="content">
        <strong><?php $_($title); ?></strong>
        <div class="bits-login">
          <span>Welcome <?php $_($name); ?></span>
          <a href="<?php $_($logout); ?>" class="button">Log Out</a>
        </div>
          <a class="mdl-navigation__link"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">event</i>Event Admin</a>
      </div>

      <main class="mdl-layout__content mdl-color-grey-100">
        <div class="bits-content">

<?php /*

<?php if ($error) : ?>
  <div class="box error" onclick="this.style.opacity = 0;"><?php $_($error); ?></div>

<?php endif; ?>
<?php if ($warning) : ?>
  <div class="box warning" onclick="this.style.opacity = 0;"><?php $_($warning); ?></div>

<?php endif; ?>
<?php if ($success) : ?>
  <div class="box success" onclick="this.style.opacity = 0;"><?php $_($success); ?></div>

<?php endif; ?>
*/ ?>    <main class="bits-layout__content content">
      <div>
