<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title><?php echo $title; ?></title>
<?php if ($description) : ?>
	<meta name="description" content="<?php echo $description; ?>" />
<?php endif; ?>
<?php if ($keywords) : ?>
	<meta name="keywords" content="<?php echo $keywords; ?>" />
<?php endif; ?>
<?php foreach ($styles as $style) : ?>
	<link rel="<?php echo $style['rel']; ?>" type="text/css" href="<?php echo $style['href']; ?>"<?php if ($style['media']) : ?> media="<?php echo $style['media']; ?>"<?php endif; ?> />
<?php endforeach; ?>
<?php foreach ($scripts as $script) : ?>
	<script type="text/javascript" src="<?php echo $script; ?>"></script>
<?php endforeach; ?>
</head>
<body>