<?php echo $header; ?>

<div id="my-account" class="block">
  <div class="row"><a href="<?php $_($mailing); ?>"><span class="icon mailing">&nbsp;</span>Change e-mail preferences</a></div>
  <div class="row"><a href="<?php $_($reset); ?>"><span class="icon password">&nbsp;</span>Change Password</a></div>
  <div class="row"><a href="<?php $_($change_email); ?>"><span class="icon change-email">&nbsp;</span>Change e-mail</a></div>
</div>
<hr/>
<div id="my-details" class="block">
  <div class="row"><a href="<?php $_($personal_details); ?>"><span class="icon ooc">&nbsp;</span>Your Details (OOC)</a></div>
  <div class="row"><a href="<?php $_($character_details); ?>"><span class="icon ic">&nbsp;</span>Character Details (IC)</a></div>
</div>


<?php echo $footer;