<?php echo $header; ?>

<div id="ic-form">
  <form action="<?php $_($character); ?>" method="post" enctype="multipart/form" class="advanced-form">
    <fieldset class="row double">
      <legend>Character name:</legend>
      <div class="field<?php if (!empty($error_character_name)) echo ' error'; ?>">
        <input type="text" name="character_name" id="character_name" placeholder="Your character name" value="<?php $_($character_name); ?>" required="required" />
        <label for="firstname">Actual name</label>
      </div>
      <div class="field">
        <input type="text" name="alias" id="alias" placeholder="Preferred name" value="<?php $_($alias); ?>" />
        <label for="alias">Preferred name</label>
      </div>
    </fieldset>

    <fieldset name="address">
      <legend>Character background:</legend>
      <div class="block double">
        <div class="field">
          <select name="race" id="race">
<?php foreach ($racial_types as $type) : ?>
            <option value="<?php echo strtosafelower($type); ?>"<?php if (strtosafelower($type) == $race) echo ' selected="selected"'; ?>><?php $_($type); ?></option>
<?php endforeach; ?>
            <option value="other"<?php if (strtosafelower($race) == 'other') echo ' selected="selected"'; ?>>Lammie supported race</option>
          </select>
          <label for="race">Racial Group</label>
          <div class="other<?php if (!$race_other) echo ' is-hidden'; ?>" id="race-other">
            <input type="text" name="race_other" id="race-other-name" value="<?php $_($race_other); ?>" placeholder="Race and Lammie ID"<?php if ($race_other) echo ' required="required"'; ?> />
            <label for="race-other-name">Lammie supported race</label>
          </div>
        </div>
        <div class="field">
          <select name="gender" id="gender">
<?php foreach ($gender_types as $type) : ?>
            <option value="<?php echo strtosafelower($type); ?>"<?php if (strtosafelower($type) == $gender) echo ' selected="selected"'; ?>><?php $_($type); ?></option>
<?php endforeach; ?>
          </select>
          <label for="gender">Gender</label>
        </div>
      </div>
      <div class="block<?php echo $group_label ? ' double' : ' single'; ?>" id="faction-block">
        <div class="field">
          <select name="faction" id="faction">
<?php foreach ($faction_names as $faction_name) : ?>
            <option value="<?php echo strtosafelower($faction_name); ?>"<?php if (strtosafelower($faction_name) == $faction) echo ' selected="selected"'; ?>><?php $_($faction_name); ?></option>
<?php endforeach; ?>
          </select>
          <label for="faction">Faction</label>
        </div>
<?php if ($group_label) : ?>
        <div class="field">
          <select name="group" id="group">
            <option value=""<?php if ($group == '') echo ' selected="selected"'; ?>>None</option>
<?php 	foreach ($group_names as $group_name) : ?>
            <option value="<?php echo strtosafelower($group_name); ?>"<?php if (strtosafelower($group_name) == $group) echo ' selected="selected"'; ?>><?php $_($group_name); ?></option>
<?php 	endforeach; ?>
            <option value="other"<?php if ($group == 'other' || $group == 'Other (enter name below)') echo ' selected="selected"'; ?>>Other (please enter name)</option>
          </select>
          <label for="group"><?php $_($group_label); ?></label>
          <div class="other<?php if (!$group_other) echo ' is-hidden'; ?>" id="group-other">
            <input type="text" name="group_other" id="group-other-name" value="<?php $_($group_other); ?>" placeholder="Group Name (other)"<?php if ($group_other) echo 'required="required"'; ?> />
            <label for="group-other-name">Group name (other)</label>
          </div>
        </div>
<?php endif; ?>
      </div>
      <div class="block<?php echo $ancestor_names ? ' double' : ' single'; ?>">
<?php if ($ancestor_names) : ?>
        <div class="field">
          <select name="ancestor" id="ancestor">
            <option value=""<?php if ($ancestor == '') echo ' selected="selected"'; ?>>None</option>
<?php 	foreach ($ancestor_names as $ancestor_name) : ?>
            <option value="<?php echo strtosafelower($ancestor_name); ?>"<?php if (strtosafelower($ancestor_name) == $ancestor) echo ' selected="selected"'; ?>><?php $_($ancestor_name); ?></option>
<?php 	endforeach; ?>
            <option value="other"<?php if ($ancestor == 'other' || $ancestor == 'Other (enter name below)') echo ' selected="selected"'; ?>>Other (please enter name)</option>
          </select>
          <label for="ancestor">Ancestor</label>
        </div>
        <div class="other field<?php if ($ancestor != 'other' && $ancestor != 'Other (enter name below)') echo ' is-hidden'; ?>" id="ancestor-other">
          <input type="text" name="ancestor_other" id="ancestor-other" value="<?php $_($ancestor_other); ?>"<?php if ($ancestor_other) echo ' required="required"'; ?> />
          <label for="ancestor-other">Ancestor (leave blank for none)</label>
        </div>
<?php else : ?>
        <div class="field">
          <input type="hidden" name="ancestor" value="other" />
          <input type="text" name="ancestor_other" id="ancestor-other" value="<?php echo $ancestor_other; ?>" />
          <label for="ancestor-other">Ancestor (leave blank for none)</label>
        </div>
<?php endif; ?>
      </div>

<?php if ($location_label && $location_names) : ?>
      <div class="block single">
        <div class="field">
          <select name="location" id="location">
            <option value=""<?php if ($location == '') echo ' selected="selected"'; ?>>Not listed</option>
<?php 	foreach ($location_names as $location_name) : ?>
            <option value="<?php echo strtosafelower($location_name); ?>"<?php if (strtosafelower($location_name) == $location) echo ' selected="selected"'; ?>><?php $_($location_name); ?></option>
<?php 	endforeach; ?>
          </select>
          <label for="location"><?php echo $location_label; ?></label>
        </div>
      </div>
<?php endif; ?>

      <div class="block double guilds" id="guild-block">
        <label>Guilds:</label>
<?php if (!empty($my_guilds)) : ?>
        <ul class="guild-list">
<?php 	foreach ($my_guilds as $guild_id) : ?>
          <li><input type="hidden" name="guild[]" value="<?php echo $guild_id; ?>" /><?php echo $guild_names[$guild_id]; ?></li>
<?php 	endforeach; ?>
        </ul>
<?php endif; ?>
        <div class="field" id="gins">
          <select id="guild-button">
            <option value=""></option>
<?php foreach ($guild_names as $guild_id => $guild_name) : ?>
            <option value="<?php echo $guild_id; ?>"<?php if (!empty($guilds) && in_array($guild_id, $guilds)) echo ' disabled="disabled"'; ?>><?php echo $guild_name; ?></option>
<?php endforeach; ?>
          </select>
          <label for="guild-button">Add Guild</label>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Character Build<span class="points" id="character-points"></span></legend>
      <div class="block double character-skills">
<?php foreach (array('left'=>array('offence', 'defence', 'knowledge'), 'right'=>array('magic')) as $groups) : ?>
        <div class="field">
<?php 	foreach ($groups as $group) : ?>
<?php 		$group = $character_skills[$group]; ?>
          <strong><?php $_($group['name']); ?></strong>
          <ul>
<?php 		foreach ($group['children'] as $skill) : ?>
            <li>
<?php 			if ($skill['cost']) : ?>
              <label for="<?php echo $skill['key']; ?>">
                <input type="<?php echo type($skill); ?>" name="cs[<?php echo $skill['key']; ?>]" id="<?php echo $skill['key']; ?>" value="<?php echo $skill['key']; ?>"<?php if (in_array($skill['key'], $my_character_skills)) echo ' checked="checked"'; ?> data-cost="<?php echo (int)$skill['cost']; ?>" />
                <span><?php $_($skill['name']); ?><span class="cost"><?php $_($skill['cost']); ?></span></span>
              </label>
<?php 			else : ?>
              <span><?php $_($skill['name']); ?></span>
<?php 			endif; ?>
<?php 			if (isset($skill['children'])) : ?>
              <ul<?php if ($skill['type'] == 'incremental') echo ' class="incremental"'; ?>>
<?php 				foreach ($skill['children'] as $child) : ?>
                <li>
<?php						if ($child['cost']) : ?>
                  <label for="<?php echo $child['key']; ?>">
                    <input type="<?php echo type($skill); ?>" name="cs[<?php echo $skill['type'] == 'radio' ? $skill['key'] : $child['key']; ?>]" id="<?php echo $child['key']; ?>" value="<?php echo $child['key']; ?>"<?php if (in_array($child['key'], $my_character_skills)) echo ' checked="checked"'; ?> data-cost="<?php echo (int)$child['cost']; ?>" />
                    <span><?php $_($child['name']); ?><span class="cost"><?php $_($child['cost']); ?></span></span>
                  </label>
<?php 					else : ?>
                  <span class="name"><?php $_($child['name']); ?></span>
<?php 					endif; ?>
                </li>
<?php 				endforeach; ?>
              </ul>
<?php 			endif; ?>
            </li>
<?php 		endforeach; ?>
          </ul>
<?php 	endforeach; ?>
        </div>
<?php endforeach; ?>
      </div>
    </fieldset>

    <fieldset>
      <legend>Notes and Information</legend>
      <div class="block" id="notes-block">
        <label for="notes">IC Notes (e.g. Bloodline)</label>
        <div class="group">
          <textarea name="notes" id="notes" cols="50" rows="5" placeholder="Notes"><?php $_($notes); ?></textarea>
          <div><small>Please enter any IC notes that are relevant, this can
          include items such as bloodlines</small></div>
        </div>
      </div>
      <div class="block" id="lammies-block">
        <label for="lammies">Items &amp; Powers</label>
        <div class="group">
          <textarea name="lammies" id="lammies" cols="50" rows="5" placeholder="Special items, powers, creatures"><?php $_($lammies); ?></textarea>
          <div><small>Please list (one per line) any lammies you intend to
          bring with you, including any special items, powers or creature
          cards.  Lammies must be brought with you to events</small></div>
        </div>
      </div>
    </fieldset>

    <fieldset id="osps">
      <legend>Occupational Skill Points</legend>
      <div class="block double">
        <div class="field">
          Lookup:
          <input type="text" class="lookup" disabled="disabled" />
        </div>
        <div class="field osp-list">
<?php foreach ($my_osps as $osp) : ?>
          <div data-key="<?php echo $osp['short_name']; ?>"<?php if ($osp['has_other']) echo ' class="has-other"'; ?>>
<?php 	if (!$osp['has_other']) : ?>
            <input type="hidden" name="osp[<?php echo $osp['osp_id'] . $osp['idx']; ?>]" value="<?php echo $osp['short_name']; ?>" />
<?php 	endif; ?>
            <span class="name"><?php $_($osp['name']); ?></span>
<?php 	if ($osp['has_other']) : ?>
            <input type="text" name="osp[<?php echo $osp['osp_id']; ?>][]" value="<?php $_($osp['osp_other']); ?>" required="required" />
<?php 	endif; ?>
          </div>
<?php endforeach; ?>
        </div>
      </div>
    </fieldset>

    <div class="row center">
      <input type="submit" value="Save Your Details (IC)" class="button" />
    </div>
  </form>
</div>

<script type="text/javascript">//<!--
requirejs.config({
  paths: {
    fuse: ['//cdnjs.cloudflare.com/ajax/libs/fuse.js/2.3.0/fuse.min'],
    autoComplete: ['//cdnjs.cloudflare.com/ajax/libs/JavaScript-autoComplete/1.0.4/auto-complete']
  }
});
require(['details-ic'], function(form) {
  new form({
    groupSelect: $('#group'),
    raceSelect: $('#race'),
    ancestorSelect: $('#ancestor'),
    guildBlock: $('#guild-block'),
    maxCharacterPoints: <?php echo (int)$max_character_points; ?>,
    characterSkills: $('#character-skills'),
    characterPoints: $('#character-points'),
    ospBlock: $('#osps'),
    ospUrl: '<?php $_($osp_url); ?>'
  });
});


//--></script>
<?php echo $footer;

function type($skill) {
	if ($skill['type'] == 'incremental') {
		return 'checkbox';
	} else {
		return $skill['type'];
	}
}