<?php echo $header; ?>
      <p>This online booking system runs on Bitsand, a web-based booking system for LRP events. Bitsand is copyright (c) <a href="<?php $_($link_repository); ?>">The Bitsand Project<?php if ($version) $_(' ' . $version); ?></a>.</p>

      <p>Found a bug? <a href="<?php $_($link_issues); ?>">Please Report it</a>.</p>

      <p>Bitsand is free software; you can redistribute it and/or modify it under the terms of the <a href= "<?php $_($link_license); ?>" target="_blank">GNU General Public License</a> as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.<br>
<?php echo $footer; ?>