
  </div><!-- .content -->
  <footer id="footer">
    <div class="content">
      <p>This online booking system runs on Bitsand, a web-based booking system for LRP events. Bitsand is copyright &copy;<a href="<?php $_($link_download); ?>">The Bitsand Project<?php if ($version) $_(' ' . $version); ?></a>.</p>
    </div>
  </footer>
<?php foreach ($scripts as $script) : ?>
  <script type="text/javascript" src="<?php $_($script['href']); ?>"<?php if (!empty($script['defer'])) echo ' defer'; ?>></script>
<?php endforeach; ?>
</body>
</html>