<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title><?php $_($title); ?></title>
<?php if ($description) : ?>
  <meta name="description" content="<?php $_($description); ?>" />
<?php endif; ?>
<?php if ($keywords) : ?>
  <meta name="keywords" content="<?php $_($keywords); ?>" />
<?php endif; ?>
<?php foreach ($styles as $style) : ?>
  <link rel="<?php echo $style['rel']; ?>" type="text/css" href="<?php $_($style['href']); ?>"<?php if ($style['media']) : ?> media="<?php echo $style['media']; ?>"<?php endif; ?> />
<?php endforeach; ?>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>
  <script type="text/javascript">
  requirejs.config({
    baseUrl: '<?php echo $base_path; ?>scripts/',
<?php if (defined('DEVELOPMENT')) echo "     urlArgs: 'bust=' + (new Date()).getTime(),"; ?>
    paths: {
      domReady: ['//cdnjs.cloudflare.com/ajax/libs/require-domReady/2.0.1/domReady.min'],
      lzstring: ['//cdnjs.cloudflare.com/ajax/libs/lz-string/1.4.4/lz-string.min'],
      jspdf: ['//cdnjs.cloudflare.com/ajax/libs/jspdf/1.2.61/jspdf.min'],
      html2canvas: ['//cdn.rawgit.com/niklasvh/html2canvas/0.5.0-alpha2/dist/html2canvas.min'],
      fuse: ['//cdnjs.cloudflare.com/ajax/libs/fuse.js/2.3.0/fuse.min'],
      autoComplete: ['//cdnjs.cloudflare.com/ajax/libs/JavaScript-autoComplete/1.0.4/auto-complete.min']
    }
  });
  </script>
<?php foreach ($scripts as $script) : ?>
  <script type="text/javascript" src="<?php $_($script); ?>"></script>
<?php endforeach; ?>
<?php if ($favicon) : ?>
  <link rel="shortcut icon" href="<?php $_($favicon); ?>" />
<?php endif; ?>
<?php if ($rss_feed) : ?>
  <link rel="alternate" type="application/rss+xml" href="<?php $_($rss_feed); ?>" title="<?php echo $_($rss_feed_title); ?>" />
<?php endif; ?>
</head>
<body>
  <header id="login-header">
    <div class="content">
      <strong><?php $_($title); ?></strong>
      <div class="login">
<?php if ($show_login) : ?>
        <form action="<?php echo $login; ?>" method="post">
          <label for="email">Log In:</label>
          <input type="email" name="email" id="email" placeholder="Registered e-mail" value="" required="required" />
          <input type="password" name="password" placeholder="Password" required="required" />
          <input type="submit" value="Log In" class="button" />
        </form>
        <a href="<?php $_($register); ?>" class="button">Register</a>
<?php elseif ($is_logged) : ?>
<?php 	if (!empty($name)) : ?>
        <span>Welcome <?php $_($name); ?></span>
<?php 	endif; ?>
        <a href="<?php $_($account); ?>" class="button">Manage Account</a>
        <a href="<?php $_($logout); ?>" class="button">Log Out</a>
<?php endif; ?>
      </div>
    </div>
  </header>
  <nav id="menu">
    <div class="content">
      <ul>
<?php foreach ($navigation as $link) : ?>
        <li<?php if ($link['selected']) echo ' selected="selected"'; ?>><a href="<?php $_($link['href']); ?>"><?php $_($link['text']); ?></a></li>
<?php endforeach; ?>
      </ul>
    </div>
  </nav>
<?php if ($error) : ?>
  <div class="box error" onclick="this.style.opacity = 0;"><?php $_($error); ?></div>

<?php endif; ?>
<?php if ($warning) : ?>
  <div class="box warning" onclick="this.style.opacity = 0;"><?php $_($warning); ?></div>

<?php endif; ?>
<?php if ($success) : ?>
  <div class="box success" onclick="this.style.opacity = 0;"><?php $_($success); ?></div>

<?php endif; ?>
  <div class="content <?php echo $route; ?>" id="content">
    <header>
      <h1><?php $_($page_title); ?></h1>
    </header>