<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title><?php $_($title); ?></title>
<?php if ($description) : ?>
  <meta name="description" content="<?php $_($description); ?>" />
<?php endif; ?>
<?php if ($keywords) : ?>
  <meta name="keywords" content="<?php $_($keywords); ?>" />
<?php endif; ?>
<?php foreach ($styles as $style) : ?>
  <link rel="<?php echo $style['rel']; ?>" type="text/css" href="<?php $_($style['href']); ?>"<?php if ($style['media']) : ?> media="<?php echo $style['media']; ?>"<?php endif; ?> />
<?php endforeach; ?>
<?php foreach ($scripts as $script) : ?>
  <script type="text/javascript" src="<?php $_($script); ?>"></script>
<?php endforeach; ?>
<?php if ($favicon) : ?>
  <link rel="shortcut icon" href="<?php $_($favicon); ?>" />
<?php endif; ?>
<?php if ($rss_feed) : ?>
  <link rel="alternate" type="application/rss+xml" href="<?php $_($rss_feed); ?>" title="<?php echo $_($rss_feed_title); ?>" />
<?php endif; ?>
</head>
<body>
  <header id="login-header">
    <div class="content">
      <h1><?php $_($title); ?></h1>
      <div class="login">
<?php if ($show_login) : ?>
        <form action="<?php echo $login; ?>" method="post">
          <label for="email">Log In:</label>
          <input type="email" name="email" id="email" placeholder="Registered e-mail" value="" />
          <input type="password" name="password" placeholder="Password" />
          <input type="submit" value="Log In" class="button" />
        </form>
        <a href="<?php $_($register); ?>" class="button">Register</a>
<?php elseif ($is_logged) : ?>
<?php 	if (!empty($name)) : ?>
        <span>Welcome <?php $_($name); ?></span>
<?php 	endif; ?>
        <a href="<?php $_($account); ?>" class="button">Manage Account</a>
        <a href="<?php $_($logout); ?>" class="button">Log Out</a>
<?php endif; ?>
      </div>
    </div>
  </header>
  <nav id="menu">
    <div class="content">
      <ul>
<?php foreach ($navigation as $link) : ?>
        <li<?php if ($link['selected']) echo ' selected="selected"'; ?>><a href="<?php $_($link['href']); ?>"><?php $_($link['text']); ?></a></li>
<?php endforeach; ?>
      </ul>
    </div>
  </nav>
<?php if ($error) : ?>
  <div class="box error" onclick="this.style.opacity = 0;"><?php $_($error); ?></div>

<?php endif; ?>
<?php if ($warning) : ?>
  <div class="box warning" onclick="this.style.opacity = 0;"><?php $_($warning); ?></div>

<?php endif; ?>
<?php if ($success) : ?>
  <div class="box success" onclick="this.style.opacity = 0;"><?php $_($success); ?></div>

<?php endif; ?>
  <div class="content" id="content">
